[package]
org = "ym"
name = "bal_pack_demo"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[persist]
datastore = "inmemory"
module = "bal_pack_demo"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.1.0"

